### ISSUE TITLE
Enemy and character can be merged

### ISSUE THREAD

**Issue by TheLinoman** [Deadpoodle/somedumbthing#1]
If enemny and character share many properties. Better use an abstract model that includes both. Character and enemy can then just extend from the same class.

Example (I changed the names):
public abstract class Character
-public class Hero extends Character
-public class NPC extends Character
-public class Enemy extends Character
-pubic class Boss extends Enemy

**Comment by Deadpoodle** [comment]
I hand you a commitburger
