### ISSUE TITLE
Item and weapon relation

### ISSUE THREAD

**Issue by TheLinoman** [Deadpoodle/somedumbthing#2]
public class Item

public class Weapon extends Item
 private int DMG
-public int dealDamage()

public class Bow extends Weapon
-private int quiverAmmo
@Override
-public int dealDamage() {
 if(quiverAmmo > 0) {
    quiverAmmo--;
    return DEX * bowDMG
 }
}

public class Sword extends Weapon
  @Override
   dealDamage()
      return  DMG * STR

**Comment by Deadpoodle** [comment]
u smrt
